import test from 'node:test';import assert from 'node:assert/strict';
import { emptyData, validateData, makeBackup, parseBackup, planImport, removeCycle, removeField } from '../lib/domain/farm.ts';
import { summaryFromDemo, validateScan } from '../lib/domain/scans.ts';
const meta=id=>({id,schema_version:1,created_at:'2026-10-06T10:00:00.000Z',updated_at:'2026-10-06T10:00:00.000Z',origin:'demo'});
const result={mode:'mock',modelVersion:'interface-mock-v1',condition:'Synthetic demo label',confidence:0.82,crop:'Synthetic crop',uncertaintyThreshold:0.7,summary:'Test-only',uncertainMessage:'Test-only'};
const summary=(id='scan',cycle=null)=>summaryFromDemo(result,meta(id),cycle);
function data(){return {...emptyData(),farms:[{...meta('farm'),name:'Synthetic farm',language:'en',timezone:'Asia/Kolkata'}],fields:[{...meta('field'),farm_id:'farm',name:'Synthetic field',region:null,area:null,water:'unknown',location:null}],cycles:[{...meta('cycle'),field_id:'field',crop:'Synthetic crop',variety:null,status:'planned',sowing_date:null,stage:null,stage_recorded_at:null,season:null}],scans:[summary('linked','cycle'),summary('unlinked')]};}
test('demo summary records no prediction, confidence, image, filename, coordinates or executable content',()=>{const s=summary();assert.equal(s.origin,'demo');assert.equal(s.availability,'simulation');assert.equal(s.predicted_class,null);assert.equal(s.confidence,null);const clean=validateScan({...s,photo:'data:private',filename:'private.jpg',location:{latitude:0,longitude:0},code:'eval()'});assert.deepEqual(clean,s);assert.throws(()=>summaryFromDemo({...result,mode:'onnx'},meta('scan'),null),/evaluated/);});
test('invalid modes, forged predictions, inconsistent origins and invalid timestamps reject',()=>{for(const patch of [{availability:'real'},{confidence:0.8},{predicted_class:'disease'},{origin:'user'},{screened_at:'2026-02-30T00:00:00Z'},{screened_at:'2099-01-01T00:00:00Z'},{availability:'unavailable',demo_label:'fake'}])assert.throws(()=>validateScan({...summary(),...patch}));assert.doesNotThrow(()=>validateScan({...summary(),availability:'unavailable',demo_label:null,origin:'user'}));});
test('scan references and IDs are validated; backups round-trip and conflict without overwriting',()=>{const d=data();assert.deepEqual(parseBackup(JSON.stringify(makeBackup(d))).data.scans,d.scans);assert.equal(planImport(d,structuredClone(d)).additions,0);const changed=structuredClone(d);changed.scans[0].demo_label='Changed demo';assert.equal(planImport(d,changed).conflicts.length,1);assert.equal(planImport(d,changed).merged.scans[0].demo_label,d.scans[0].demo_label);assert.equal(planImport(d,changed,'backup').merged.scans[0].demo_label,'Changed demo');d.scans[0].cycle_id='missing';assert.throws(()=>validateData(d));d.scans=[summary('field')];assert.throws(()=>validateData(d));});
test('v2 migration preserves calendar and v1 migration preserves cycles without invented scans',()=>{const d=data();d.schema_version=2;delete d.scans;delete d.soil_tests;delete d.expenses;delete d.harvests;delete d.sales;const b={schema_version:2,application_version:'farm-m3-v2',exported_at:meta('x').created_at,includes_coordinates:false,data:d};const migrated=parseBackup(JSON.stringify(b));assert.equal(migrated.schema_version,6);assert.deepEqual(migrated.data.tasks,d.tasks);assert.deepEqual(migrated.data.scans,[]);d.schema_version=1;delete d.tasks;assert.deepEqual(validateData(d).scans,[]);assert.throws(()=>validateData({...d,scans:[]}));});
test('cycle/field deletion removes linked summaries and preserves unlinked summaries',()=>{const d=data();assert.deepEqual(removeCycle(d,'cycle').scans.map(s=>s.id),['unlinked']);assert.deepEqual(removeField(d,'field').scans.map(s=>s.id),['unlinked']);assert.equal(d.scans.length,2);});
