"use client";
import { useState } from 'react';
import { estimateScenario, SCENARIO_COSTS, type ScenarioInput } from '@/lib/domain/scenario';
import { formatINR } from '@/lib/domain/season-records';
import { type Field } from '@/lib/domain/farm';
import { DocumentLink } from '@/components/document-link';

const empty = (): ScenarioInput => ({ area: '', area_unit: 'ha', yield_kg_ha: '', price_rupees_kg: '', costs: SCENARIO_COSTS.map(() => '') });
export function ScenarioCalculator({field}:{field?:Field}={}) {
  const [input, setInput] = useState<ScenarioInput>(()=>({...empty(),area:field?.area?String(field.area.value):'',area_unit:field?.area?.unit??'ha'})), [result, setResult] = useState<ReturnType<typeof estimateScenario> | null>(null), [error, setError] = useState(''), [sample, setSample] = useState(false);
  function update(next: ScenarioInput) { setInput(next); setResult(null); setError(''); }
  return <section id="calculator" className="hub-section" aria-labelledby="calculator-title">
    <div className="hub-section-heading"><div><p className="eyebrow">Understand your numbers</p><h2 id="calculator-title">Profit scenario calculator</h2><p>Explore a scenario using your own expected harvest, selling price and costs. These assumptions stay on this page.</p></div><DocumentLink href="/records">Review actual season records →</DocumentLink></div>
    <div className="scenario-layout"><form className="scenario-form" onSubmit={event => { event.preventDefault(); try { setResult(estimateScenario(input)); setError(''); } catch (cause) { setResult(null); setError(cause instanceof Error ? cause.message : 'Check the scenario inputs.'); } }}>
      <h3>Your assumptions</h3><div className="scenario-fields"><label>Land area<input type="text" inputMode="decimal" required value={input.area} onChange={event => update({ ...input, area: event.target.value })} placeholder="e.g. 1" /></label><label>Area unit<select value={input.area_unit} onChange={event => update({ ...input, area_unit: event.target.value as ScenarioInput['area_unit'] })}><option value="ha">Hectares</option><option value="acre">Acres</option><option value="m2">Square metres</option></select></label><label>Expected harvest (kg per hectare)<input type="text" inputMode="decimal" required value={input.yield_kg_ha} onChange={event => update({ ...input, yield_kg_ha: event.target.value })} placeholder="Your estimate, not a crop default" /></label><label>Expected selling price (₹ per kg)<input type="text" inputMode="decimal" required value={input.price_rupees_kg} onChange={event => update({ ...input, price_rupees_kg: event.target.value })} placeholder="Your expected price" /></label></div>
      <fieldset><legend>Total costs for this field (₹)</legend><p className="hub-caption">Enter every category. Use 0 for a known zero; leave nothing unknown.</p><div className="scenario-fields">{SCENARIO_COSTS.map((name, index) => <label key={name}>{name}<input type="text" inputMode="decimal" required value={input.costs[index]} onChange={event => update({ ...input, costs: input.costs.map((value, position) => position === index ? event.target.value : value) })} placeholder="₹ for the whole field" /></label>)}</div></fieldset>
      <div className="button-row"><button className="button button-primary" type="submit">Calculate scenario</button><button className="button hub-button-outline" type="button" onClick={() => { update({ area: '1', area_unit: 'ha', yield_kg_ha: '1000', price_rupees_kg: '20', costs: ['1000', '500', '2000', '500', '250', '250'] }); setSample(true); }}>Try sample numbers</button><button className="text-button" type="button" onClick={() => { update(empty()); setSample(false); }}>Clear scenario</button></div>
      {error && <p role="alert" className="form-error">{error}</p>}
    </form><aside className="scenario-result" aria-live="polite"><span className="hub-tag">{sample ? 'Illustrative sample assumptions' : 'Your entered assumptions'}</span><h3>What this scenario shows</h3>{result ? <dl><div><dt>Expected harvest</dt><dd>{result.harvest_kg.toLocaleString('en-IN', { maximumFractionDigits: 3 })} kg</dd></div><div><dt>Expected gross receipts</dt><dd>{formatINR(result.revenue_minor)}</dd></div><div><dt>Entered total costs</dt><dd>{formatINR(result.total_cost_minor)}</dd></div><div className="scenario-margin"><dt>Receipts minus entered costs</dt><dd>{formatINR(result.margin_minor)}</dd></div></dl> : <p>Fill in your assumptions and calculate to see harvest quantity, expected receipts and the balance after entered costs.</p>}<p>Expected receipts = area in hectares × expected kg per hectare × expected ₹ per kg.</p><p className="hub-caption">A scenario is not a yield forecast or complete profit. Unentered costs, losses, financing and price changes can change the result. Receipts are rounded once to the nearest paise. Actual records are managed separately.</p></aside></div>
  </section>;
}
