"use client";
import { useEffect, useRef, useState } from 'react';
import { DocumentLink } from '@/components/document-link';
import { type Field, type Snapshot } from '@/lib/domain/farm';
import { SOIL_METRICS } from '@/lib/domain/soil';
import { WeatherClient, setupWeatherTransport, weatherFresh, type Weather } from '@/lib/providers/weather';
import { WRB_CLASSES, type MapPoint, type MappedSoil } from '@/lib/providers/field-context';
export function FieldEnvironment({snapshot,field,point=field.location,initialWeather=null,initialSoil=null,onWeather,onSoil}:{snapshot:Snapshot;field:Field;point?:MapPoint|null;initialWeather?:Weather|null;initialSoil?:MappedSoil|null;onWeather:(weather:Weather|null)=>void;onSoil?:(soil:MappedSoil|null)=>void}) {
  const [weather,setWeather]=useState(initialWeather),[soil,setSoil]=useState(initialSoil),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[soilStatus,setSoilStatus]=useState(''),[clock,setClock]=useState(0);
  const client=useRef<WeatherClient|null>(null),abort=useRef<AbortController|null>(null),epoch=useRef(0);
  useEffect(()=>{const start=setTimeout(()=>setClock(Date.now()),0),timer=setInterval(()=>setClock(Date.now()),15000),generation=epoch;return()=>{clearTimeout(start);clearInterval(timer);generation.current++;client.current?.clear();abort.current?.abort();};},[]);
  const tests=snapshot.soil_tests.filter(test=>test.field_id===field.id),latest=[...tests].sort((a,b)=>b.sample_date.localeCompare(a.sample_date)||b.created_at.localeCompare(a.created_at))[0];
  const demo=field.origin==='demo'||snapshot.farms.find(f=>f.id===field.farm_id)?.origin==='demo'||latest?.origin==='demo';
  function revoke(){epoch.current++;client.current?.clear();abort.current?.abort();setConsent(false);setBusy(false);setWeather(null);setSoil(null);onWeather(null);onSoil?.(null);setStatus('Online context cleared. No further sharing until you choose it.');setSoilStatus('');}
  async function lookup(){
    if(!point||!consent||busy)return;
    const token=++epoch.current,c=new AbortController();abort.current?.abort();abort.current=c;setBusy(true);setStatus('Checking weather…');setSoilStatus('Checking mapped soil…');
    client.current??=new WeatherClient(setupWeatherTransport());
    await Promise.allSettled([
      client.current.get(point.latitude,point.longitude,true).then(value=>{if(epoch.current===token){setWeather(value);onWeather(value);setClock(Date.now());setStatus('Weather estimates refreshed.');}}).catch(failure=>{if(epoch.current===token)setStatus(failure instanceof Error?failure.message:'Weather unavailable.');}),
      fetch('/api/soil-context',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:point.latitude,longitude:point.longitude}),signal:AbortSignal.any([c.signal,AbortSignal.timeout(15000)]),cache:'no-store'}).then(async response=>{if(!response.ok)throw Error('Mapped soil unavailable.');const value=await response.json() as MappedSoil;if(value.kind!=='soil_map'||!WRB_CLASSES.includes(value.soil_class)||value.reference_year!==null||value.source!=='https://maps.isric.org/'||!Number.isFinite(Date.parse(value.fetched_at)))throw Error('Mapped soil unavailable.');if(epoch.current===token){setSoil(value);onSoil?.(value);setSoilStatus('Mapped soil retrieved.');}}).catch(()=>{if(epoch.current===token)setSoilStatus('Mapped soil unavailable. Measured entries remain available.');})
    ]);
    if(epoch.current===token)setBusy(false);
  }
  return <div className="environment-section"><div className="dashboard-sharing"><div><h3>Field context</h3><p>{point?'Refresh shares the confirmed point through this app’s server with Open-Meteo and ISRIC. Permission lasts for this page.':weather||soil?'Showing estimates fetched during setup. Your point was not carried across; refreshing needs a confirmed field location.':'No confirmed location is available on this page. Add one in field settings to connect weather and mapped soil.'}</p></div>{point?<div><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>e.target.checked?setConsent(true):revoke()}/>Allow weather & soil lookup</label><div className="button-row"><button type="button" className="button button-secondary" disabled={!consent||busy} onClick={()=>void lookup()}>{busy?'Refreshing…':'Refresh field context'}</button>{(consent||weather||soil)&&<button type="button" className="text-button" onClick={revoke}>Stop sharing & clear context</button>}</div></div>:<div className="button-row"><DocumentLink href="/farm#manage-fields">Add field location</DocumentLink>{(weather||soil)&&<button type="button" className="text-button" onClick={revoke}>Clear temporary context</button>}</div>}</div>
    <div className="environment-grid"><section id="forecast" className="dashboard-card forecast-card" aria-label="Weather forecast"><div className="dashboard-card-heading"><div><p className="eyebrow">Open-Meteo · model estimates</p><h2>Weather & seven-day forecast</h2></div>{weather&&<span className={weatherFresh(weather,clock)?'status-chip':'status-chip status-stale'}>{weatherFresh(weather,clock)?'Fresh estimates':'Stale estimates'}</span>}</div>{status&&<p role="status" className="dashboard-caption">{status}</p>}{weather?<><div className="weather-now"><strong>{weather.current.temperature===null?'—':`${weather.current.temperature}°C`}</strong><dl><div><dt>Humidity</dt><dd>{weather.current.humidity===null?'Unavailable':`${weather.current.humidity}%`}</dd></div><div><dt>Wind</dt><dd>{weather.current.wind===null?'Unavailable':`${weather.current.wind} m/s`}</dd></div><div><dt>Current rain estimate</dt><dd>{weather.current.precipitation===null?'Unavailable':`${weather.current.precipitation} mm / ${weather.interval_seconds/60} min`}</dd></div></dl></div><div className="forecast-days">{weather.days.map(day=><article key={day.date}><h3>{new Date(`${day.date}T00:00:00Z`).toLocaleDateString('en-IN',{weekday:'short',timeZone:'UTC'})}</h3><span>{day.date.slice(5)}</span><strong>{day.maximum??'—'}° / {day.minimum??'—'}°</strong><span className="rain-label">{day.precipitation===null?'Rain unavailable':`${day.precipitation} mm`}</span></article>)}</div><p className="dashboard-caption">Daily ranges and rainfall totals use UTC days. Current estimate valid {new Date(weather.observed_at).toLocaleString('en-IN')}; retrieved {new Date(weather.fetched_at).toLocaleString('en-IN')}. Forecast issue time unavailable. <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo · CC BY 4.0</a>.</p></>:<p className="empty-state">Weather is unavailable until you allow a lookup with a confirmed field location. Your crop records and calendar still work.</p>}</section>
    <section id="soil" className="dashboard-card soil-card" aria-label="Soil information"><p className="eyebrow">Field evidence</p><h2>Your soil</h2>{soil?<div className="soil-map-summary"><span className="status-chip">Mapped estimate</span><h3>{soil.soil_class}</h3><p className="dashboard-caption">Global map cell, not a field measurement. Reference year unavailable; retrieved {new Date(soil.fetched_at).toLocaleString('en-IN')}. <a href={soil.source} target="_blank" rel="noreferrer">ISRIC · CC BY 4.0</a>.</p></div>:<p className="dashboard-caption">{soilStatus||'Mapped soil class unavailable.'}</p>}<h3>Measured soil results</h3>{latest?<><p>{demo?'Synthetic demonstration · ':''}{latest.source_kind==='soil_lab'?'Laboratory test':'Recorded field test'} · {latest.source} · sampled {latest.sample_date}</p><dl>{latest.readings.map(r=><div key={r.metric}><dt>{SOIL_METRICS[r.metric].label}</dt><dd>{r.value} {r.unit==='percent'?'%':r.unit==='g_kg'?'g/kg':r.unit}</dd></div>)}</dl><p className="dashboard-caption">Depth: {latest.depth_cm?`${latest.depth_cm.top}–${latest.depth_cm.bottom} cm`:'unknown'}. Test age and method must be checked before using results.</p></>:<p className="empty-state">No measured soil test recorded. pH and nutrients cannot be inferred from GPS or the soil map.</p>}<DocumentLink href="/records">Open soil notebook</DocumentLink></section></div>
  </div>;
}
