"use client";
import { useRef, useState, type FormEvent } from 'react';
import { GOALS, type Goal, type NextStep } from '@/lib/recommendations/next-steps';
import { todayInZone, type FarmData, type Snapshot } from '@/lib/domain/farm';
import { addDays } from '@/lib/domain/calendar';
import { FEEDBACK_STATES, feedbackKey, matchingFeedback, feedbackActive, feedbackIsDemo, recordFeedback, type FeedbackState, type ActionFeedback } from '@/lib/domain/action-feedback';
const labels:Record<FeedbackState,string>={pending:'To review',done:'Done (self-reported)',snoozed:'Snoozed',not_applicable:'Not applicable',needs_help:'Need help'};
export function NextStepsPanel({steps, demo, snapshot, fieldId, cycleId, timezone, busy, save}: {steps: NextStep[]; demo: boolean; snapshot:Snapshot; fieldId:string;cycleId:string|null;timezone:string;busy:boolean;save:(data:FarmData,message:string)=>Promise<boolean>}) {
  const [goal,setGoal]=useState<Goal>('All next steps'),[showHandled,setShowHandled]=useState(false),[selected,setSelected]=useState<string|null>(null);
  const [draft,setDraft]=useState({state:'pending' as FeedbackState,snooze:'',note:'',key:''}),[error,setError]=useState(''),[message,setMessage]=useState('');
  const operation=useRef(false),formRef=useRef<HTMLElement>(null);
  const today=todayInZone(timezone),history=snapshot.feedback.filter(f=>f.field_id===fieldId && f.cycle_id===cycleId).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)||a.id.localeCompare(b.id));
  const inFocus=steps.filter(s=>goal==='All next steps' || s.goal===goal);
  const visible=inFocus.filter(s=>showHandled || feedbackActive(matchingFeedback(snapshot,fieldId,cycleId,s),today));
  const step=steps.find(s=>s.id===selected),changed=!!step && draft.key!==feedbackKey(snapshot,fieldId,cycleId,step);
  function status(f:ActionFeedback){return f.state==='snoozed' ? `Snoozed until ${f.snooze_until}${f.snooze_until!<=today ? ' · ready to review again' : ''}` : f.state==='done' && f.step_id.startsWith('task:') ? 'Reminder reviewed' : labels[f.state];}
  function open(s:NextStep){const feedback=matchingFeedback(snapshot,fieldId,cycleId,s);setSelected(s.id);setDraft({state:feedback?.state ?? 'pending',snooze:feedback?.snooze_until ?? '',note:feedback?.note ?? '',key:feedbackKey(snapshot,fieldId,cycleId,s)});setError('');setMessage('');formRef.current?.focus();}
  async function store(s:NextStep,state:FeedbackState,snooze:string|null,note:string|null,key:string){
    if(busy || operation.current)return false;operation.current=true;setError('');setMessage('');
    try{const data=recordFeedback(snapshot,fieldId,cycleId,s,{state,snooze_until:snooze,note,input_key:key});if(!await save(data,'Step feedback saved on this device.')){setError('Feedback was not saved. Check the storage message above; reload if another tab changed the records.');return false;}setMessage('Feedback saved locally. No message or notification was sent.');return true;}
    catch(e){setError(e instanceof Error ? e.message : 'Could not save feedback.');return false;}
    finally{operation.current=false;}
  }
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(step && await store(step,draft.state,draft.state==='snoozed' ? draft.snooze || null : null,draft.note.trim() || null,draft.key))setSelected(null);}
  return <section aria-labelledby="recommendations-title" className="location-box">
    <p className="eyebrow">Personalized from your records</p><h3 id="recommendations-title">Recommended next steps</h3>
    <p>{demo ? 'Synthetic demo · ' : ''}Planning and record suggestions for this field. These are preparation steps, not prescriptions or yield predictions.</p>
    <p>Feedback stays on this device and in your farm backup. Changed inputs can bring a step back for review. Marking a suggestion done does not fill missing field data or establish that advice worked. Manage actual calendar reminders in Plan.</p>
    <label>Your focus<select value={goal} onChange={e=>setGoal(e.target.value as Goal)}>{GOALS.map(g=><option key={g}>{g}</option>)}</select></label>
    <label className="check-label"><input type="checkbox" checked={showHandled} onChange={e=>setShowHandled(e.target.checked)} />Show done, snoozed and not-applicable steps</label>
    <p aria-live="polite">{visible.length} next {visible.length===1 ? 'step' : 'steps'} shown for this focus</p>
    {error && <p className="form-error" role="alert">{error}</p>}<div aria-live="polite">{message && <p className="success-note">{message}</p>}</div>
    {visible.map(s=>{const feedback=matchingFeedback(snapshot,fieldId,cycleId,s);return <article key={s.id} className="farm-card">{feedbackIsDemo(snapshot,fieldId,cycleId,s.id) && <span className="simulation-label">Synthetic demonstration step</span>}<p className="eyebrow">{s.goal} · {s.timing}</p><h4>{s.title}</h4><p>{s.why}</p>{feedback && <p className="cycle-badge">{status(feedback)}</p>}<details><summary>Why am I seeing this?</summary><ul>{s.inputs.map(i=><li key={i}>{i}</li>)}</ul><p>Source: your local field/cycle records{s.id.startsWith('weather') ? ' and the weather availability shown above' : ''}. No agronomic rule is applied.</p></details><p><a className="button button-secondary" href={s.href}>{s.action} →</a></p><button className="button button-secondary" type="button" disabled={busy} onClick={()=>open(s)}>Update feedback for {s.title}</button></article>;})}
    {!visible.length && <p>No active steps for this focus. You can show handled steps or review saved feedback below.</p>}
    {selected && <section className="farm-card" ref={formRef} tabIndex={-1} aria-label="Step feedback form"><h4>Feedback: {step?.title ?? 'Step no longer displayed'}</h4>{step ? <><p>{step.why}</p>{changed && <p role="alert">Inputs changed while this form was open. Review the current explanation, then <button className="text-button" type="button" disabled={busy} onClick={()=>setDraft({...draft,key:feedbackKey(snapshot,fieldId,cycleId,step)})}>Use current inputs</button>. Your draft note is kept.</p>}<form onSubmit={e=>void submit(e)}><fieldset disabled={busy}><legend>Your response</legend><label>Step status<select value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value as FeedbackState})}>{FEEDBACK_STATES.map(state=><option key={state} value={state}>{state==='done' && step.id.startsWith('task:') ? 'Reminder reviewed' : labels[state]}</option>)}</select></label>{draft.state==='snoozed' && <label>Snooze until (farm local date)<input required type="date" min={addDays(today,1)} value={draft.snooze} onChange={e=>setDraft({...draft,snooze:e.target.value})} /></label>}<label>Feedback note (optional)<textarea rows={2} maxLength={500} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} /></label><p>Need help records your request locally. Nobody is contacted. A snoozed step returns on its selected local date; no notification is sent. This feedback does not complete or reschedule reminders in Plan.</p><div className="button-row"><button className="button button-primary" type="submit" disabled={changed}>Save step feedback</button><button className="text-button" type="button" onClick={()=>setSelected(null)}>Cancel feedback</button></div></fieldset></form></> : <><p>The suggestion no longer applies or is no longer due. Its saved feedback remains below.</p><button className="text-button" type="button" onClick={()=>setSelected(null)}>Close feedback form</button></>}</section>}
    <details><summary>Saved follow-ups ({history.length})</summary><p>Current and previous input contexts for this field/cycle. Previous responses do not hide changed suggestions.</p>{!history.length && <p>No feedback saved yet.</p>}{history.map(f=>{const current=steps.find(s=>s.id===f.step_id && feedbackKey(snapshot,fieldId,cycleId,s)===f.input_key);return <article className="field-item" key={f.id}>{(f.origin==='demo' || feedbackIsDemo(snapshot,fieldId,cycleId,f.step_id)) && <span className="simulation-label">Synthetic demonstration feedback</span>}<h4>{f.title}</h4><p>{status(f)} · saved {new Date(f.updated_at).toLocaleString('en',{timeZone:timezone})}</p><p>{current ? 'Matches current suggestion inputs.' : 'Previous inputs or a step no longer displayed; current suggestions need a fresh review.'}</p>{f.note && <p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{f.note}</p>}{current && <div className="button-row"><button className="text-button" disabled={busy} type="button" onClick={()=>open(current)}>Change saved feedback</button>{f.state!=='pending' && <button className="text-button" disabled={busy} type="button" onClick={()=>void store(current,'pending',null,f.note,f.input_key)}>Reopen step</button>}</div>}</article>;})}</details>
    <details><summary>Unlock seed, soil and irrigation guidance</summary><p>Regional seed comparisons and farming actions need source-backed content reviewed by an agricultural expert. No reviewed catalog is loaded yet. Record measured soil results in Records. Live sensors are unavailable; GPS cannot measure soil nutrients. Complete records help check eligibility when reviewed guidance arrives.</p></details>
  </section>;
}
