import { FARMER_SUPPORT, type SupportEntry } from './farmer-support.ts';

// Government programme screening is separate from agronomic advice and bank products.
export type AnswerKey = 'tenure' | 'family_land' | 'land_date' | 'institutional' | 'public_office' | 'government_employee' | 'pension' | 'income_tax' | 'professional' | 'water_source' | 'irrigation_benefit' | 'drip_commitment' | 'organic_group' | 'infrastructure' | 'solar';
export type SchemeCondition = { key: AnswerKey; accepted: string[]; question: string; reason: string; mismatch: string };
export type GovernmentScheme = SupportEntry & {
  scope: 'central' | 'mp'; topic: 'income' | 'credit' | 'insurance' | 'water' | 'soil' | 'seeds' | 'training' | 'infrastructure';
  conditions: SchemeCondition[]; crops?: string[]; office_checks: string[];
  screening: 'conditions' | 'office'; source_updated: string | null;
};
const condition = (key: AnswerKey, accepted: string[], question: string, reason: string, mismatch: string): SchemeCondition => ({ key, accepted, question, reason, mismatch });
const owner = condition('tenure', ['owner'], 'Do you own this field?', 'You report owning the selected field.', 'The cited MP programme requires your own agricultural land. Ask the office about other routes for tenants.');
const familyLand = condition('family_land', ['yes'], 'Does your farmer family hold cultivable land in government records?', 'You report cultivable land in your farmer family’s records.', 'Landholding farmer-family income support needs recorded cultivable land; tenancy alone does not satisfy that condition.');
const exclusion = (key: AnswerKey, question: string): SchemeCondition => condition(key, ['no'], question, `You answered No: ${question}`, `Your Yes answer meets an income-support exclusion: ${question}`);
export const INCOME_CONDITIONS: SchemeCondition[] = [familyLand,
  condition('land_date', ['before', 'inheritance'], 'Was the land held on 1 February 2019, or acquired later through inheritance after the landowner’s death?', 'Your reported land acquisition is within a published eligibility route; the revenue office must verify records.', 'The published PM-KISAN guidance excludes later acquisition through sale/gift/partition; ask the revenue office to verify your case.'),
  exclusion('institutional', 'Is the landholder an institution?'),
  exclusion('public_office', 'Does any farmer-family member hold or previously hold a listed constitutional or elected office?'),
  exclusion('government_employee', 'Is any family member a serving/retired government, public-sector or regular local-body employee, other than MTS / Class IV / Group D?'),
  exclusion('pension', 'Does any family member receive a retirement pension of ₹10,000 or more per month, excluding the MTS / Class IV / Group D exception?'),
  exclusion('income_tax', 'Did any farmer-family member pay income tax in the last assessment year?'),
  exclusion('professional', 'Is any family member a registered, practising doctor, engineer, lawyer, chartered accountant or architect?'),
];
const support = (id: string): SupportEntry => FARMER_SUPPORT.find(entry => entry.id === id)!;
const central = (id: string, topic: GovernmentScheme['topic'], conditions: SchemeCondition[], office_checks: string[], screening: GovernmentScheme['screening'] = 'conditions'): GovernmentScheme => ({ ...support(id), scope: 'central', topic, conditions, office_checks, screening, source_updated: null });
const mp = (id: string, name: string, topic: GovernmentScheme['topic'], schemeId: number, summary: string, benefit: string, conditions: SchemeCondition[], office_checks: string[], source_updated: string | null, screening: GovernmentScheme['screening'] = 'conditions'): GovernmentScheme => ({
  id, name, topic, scope: 'mp', provider: 'Madhya Pradesh government / agriculture or revenue office', categories: ['schemes'], summary, benefit,
  audience: 'Farmers meeting the published programme conditions and local selection requirements.', conditions, office_checks, screening, source_updated,
  prepare: ['Ask the responsible office for the current form and required land/cultivation, identity and bank documents. Submit documents only to the official office or portal.'],
  caution: 'This is a preliminary check of published conditions, not approval. District allocation, current guidelines and document verification can affect access.',
  availability: 'Current application window and local allocation have not been verified. Check with the responsible office before purchasing or applying.', checked_on: '2026-10-09',
  source: { label: 'MP government: programme conditions', url: `https://cmhelpline.mp.gov.in/Schmedetail.aspx?Schemeid=${schemeId}` },
  portal: { label: 'Official programme and contact details', url: `https://cmhelpline.mp.gov.in/Schmedetail.aspx?Schemeid=${schemeId}` },
});

export const MP_SCHEME_DIRECTORY = 'https://cmhelpline.mp.gov.in/KnowYourEntitleGrid.aspx?pointvalue=2&status=byschemefor';
export const GOVERNMENT_SCHEMES: readonly GovernmentScheme[] = [
  { ...central('pm-kisan', 'income', INCOME_CONDITIONS, ['Revenue office: verify family definition (husband, wife and minor children), land records/acquisition and exclusions.', 'Official portal: confirm eKYC, land seeding, bank validation and beneficiary status.']), source: { label: 'PM-KISAN revised operational guidelines', url: 'https://fw.pmkisan.gov.in/Documents/Revised%20Operational%20Guidelines%20-%20PM-Kisan%20Scheme.pdf' } },
  mp('mp-kisan-kalyan', 'Mukhyamantri Kisan Kalyan Yojana', 'income', 606, 'Madhya Pradesh income support using PM-KISAN eligibility conditions.', 'The state page lists ₹6,000 annually in three instalments, in addition to PM-KISAN for eligible beneficiaries.', INCOME_CONDITIONS, ['Contact the patwari/tehsil office to verify PM-KISAN eligibility and state beneficiary status.', 'Check payment status through SAARA; receiving one benefit does not prove the other is approved.'], '2024-08-28'),
  { ...central('kcc', 'credit', [condition('tenure', ['owner', 'tenant', 'sharecropper'], 'How do you cultivate this field?', 'KCC includes owner-cultivators, tenants, oral lessees and sharecroppers.', 'Ask your bank about the applicable farmer/SHG/JLG route.')], ['Bank: cultivation proof, credit assessment, limits, interest and repayment terms.']), source: { label: 'Department of Financial Services: agricultural credit eligibility', url: 'https://www.financialservices.gov.in/agriculture-credit' } },
  central('pmfby', 'insurance', [], ['Insurer/official portal: current district, crop and season notification, sowing/cultivation proof, deadline and policy terms. Tenants/sharecroppers may be covered.'], 'office'),
  central('rwbcis', 'insurance', [], ['Insurer: confirm this crop, district and season are notified, plus the reference station, weather trigger term sheet and deadline.'], 'office'),
  central('soil-health-card', 'soil', [], ['Block agriculture office/laboratory: sampling arrangements, report availability and any charges.'], 'conditions'),
  central('aif', 'infrastructure', [condition('infrastructure', ['yes'], 'Are you planning post-harvest or community farming infrastructure?', 'You report an infrastructure project to discuss with the programme lender.', 'This programme supports qualifying infrastructure projects, not general household income.')], ['Programme/lender: confirm eligible project, applicant type, application period, project report and lending conditions.'], 'office'),
  central('pm-kusum', 'water', [condition('solar', ['yes'], 'Are you seeking an agricultural solar pump or pump solarisation?', 'You are considering a solar agricultural pump project.', 'This programme concerns solar agricultural equipment.')], ['State implementing agency: programme extension, currently open component, pump/grid conditions, allocation and approved subsidy.'], 'office'),
  mp('mp-micro-irrigation', 'Per Drop More Crop · MP micro-irrigation', 'water', 98, 'Support for approved drip/sprinkler irrigation equipment.', 'The state page lists 55% of unit cost for small/marginal farmers and 45% for other farmers; approved cost limits need confirmation.', [owner,
    condition('water_source', ['yes'], 'Do you have a water source for irrigation?', 'You report an irrigation water source.', 'The cited programme requires an irrigation source.'),
    condition('irrigation_benefit', ['no'], 'Have you received an irrigation-equipment benefit in the last seven years?', 'You report no irrigation-equipment benefit in the last seven years.', 'The cited MP page excludes farmers who received this benefit within seven years.')], ['District agriculture office: holding-size classification, approved equipment/unit-cost limits and current lottery window.', 'Ask for approval before buying equipment; selection is by the notified lottery.'], '2026-05-20'),
  mp('mp-balram-tal', 'Balram Tal · farm pond support', 'water', 92, 'A farm-pond programme for water conservation.', 'Pond construction assistance is subject to current category, cost caps and approval. Confirm current rates locally.', [owner,
    condition('drip_commitment', ['yes'], 'Will the pond project include the required drip/sprinkler arrangement?', 'You plan the linked drip/sprinkler arrangement stated by the MP page.', 'The cited MP page requires drip/sprinkler alongside the pond.')], ['Assistant soil conservation officer: confirm private-land/site suitability, approved current guideline, allocation and construction conditions.', 'The detailed source is dated 2022 and rate descriptions differ across official district pages; no amount is calculated here.'], '2022-10-20', 'office'),
  { ...mp('mp-seed-village', 'Seed Village · seed and planting material support', 'seeds', 856, 'Subsidised seed and training through the local Seed Village programme.', 'The MP page describes support for seed for up to one acre; crop-specific rates and current allocation need office confirmation.', [owner], ['Block agriculture office: clarify one-acre support coverage versus total holding, approved seed/crop, season supply and selection.', 'Published rates are up to 50% for foodgrain and 60% for pulse/oilseed seed; no variety recommendation is made.'], '2026-05-20', 'office') },
  { ...mp('mp-food-security', 'Food & Nutrition Security · crop support', 'seeds', 834, 'Crop demonstrations, training and support in identified programme areas.', 'Assistance depends on the approved crop component and district allocation.', [owner], ['Block agriculture office: verify identified district/crop component, current guidelines, supplies and first-come/lottery selection.'], '2022-11-14', 'office'), crops: ['wheat', 'chickpea', 'rice', 'maize', 'millet', 'sugarcane', 'cotton'] },
  { ...mp('mp-oilseed-mission', 'Oilseed mission · MP crop support', 'seeds', 865, 'Oilseed crop support listed by the state under its crop-mission programmes.', 'Training and approved assistance depend on the current oilseed component.', [owner], ['District agriculture office: current mission name/component, eligible crop, allocation and first-come/lottery selection.'], '2026-05-20', 'office'), crops: ['soybean', 'mustard', 'groundnut', 'sunflower', 'sesame', 'linseed', 'oil-palm'] },
  mp('mp-atma', 'ATMA · farmer training and demonstrations', 'training', 843, 'Farmer training, demonstrations and extension activities through the block office.', 'Ask the block technical manager or ATMA project director about available sessions and farm-school activities.', [], ['Block technical manager/ATMA director: confirm current programme, farmer registration, rural coverage and required documents.'], '2022-10-20'),
  mp('mp-pkvy', 'Paramparagat Krishi Vikas Yojana · organic farming', 'training', 828, 'Support for group-based organic farming and certification.', 'Group support and approved activities depend on the current programme guidelines.', [owner,
    condition('organic_group', ['yes'], 'Do you want to join or register an organic-farming group?', 'You report interest in the group-based organic route.', 'The cited MP route uses a farmer group and group registration.')], ['ATMA project director: current cluster selection, PGS group registration, transition commitments and assistance.', 'The detailed source is dated 2022; no blanket cash or 100% subsidy is promised.'], '2022-10-20', 'office'),
  { ...mp('mp-equipment', 'MP agricultural machinery subsidy programmes', 'infrastructure', 98, 'Equipment support administered through MP’s e-Krishi Yantra portal.', 'The approved equipment, farmer category, past benefit and lottery determine support.', [], ['Agricultural engineering office: equipment-specific land/tractor requirements, repeat-benefit rules, deposit, lottery and current subsidy caps.'], null, 'office'), source: { label: 'MP Directorate of Agricultural Engineering: programmes', url: 'https://mpdage.mp.gov.in/' }, portal: { label: 'Official MP farmer equipment portal', url: 'https://farmer.mpdage.mp.gov.in/' } },
];
